// src/components/ui/KPICard.vue
<script setup lang="ts">
import type { Component } from 'vue'

interface KPICardProps {
  title: string
  value: string | number
  change?: string
  trend?: 'up' | 'down' | 'neutral'
  icon?: Component
  iconColor?: 'primary' | 'secondary' | 'accent' | 'info' | 'success' | 'warning' | 'error'
}

withDefaults(defineProps<KPICardProps>(), {
  change: '',
  trend: 'neutral',
  iconColor: 'primary'
})

const trendColors = {
  up: 'text-success',
  down: 'text-error', 
  neutral: 'text-base-content/60'
}

const iconBgColors = {
  primary: 'bg-primary/10 text-primary',
  secondary: 'bg-secondary/10 text-secondary',
  accent: 'bg-accent/10 text-accent',
  info: 'bg-info/10 text-info',
  success: 'bg-success/10 text-success',
  warning: 'bg-warning/10 text-warning',
  error: 'bg-error/10 text-error'
}
</script>

<template>
  <div class="card bg-base-100 shadow-xl hover:shadow-2xl transition-all duration-200 hover:-translate-y-1">
    <div class="card-body p-4">
      <div class="flex items-center justify-between">
        <div class="text-sm font-medium text-base-content/70">
          {{ title }}
        </div>
        <div 
          v-if="icon" 
          class="rounded-lg p-2"
          :class="iconBgColors[iconColor]"
        >
          <component :is="icon" class="size-4" />
        </div>
      </div>
      
      <div class="text-3xl font-bold tracking-tight text-base-content">
        {{ value }}
      </div>
      
      <div 
        v-if="change" 
        class="flex items-center gap-2 text-xs"
        :class="trendColors[trend]"
      >
        <span>{{ change }}</span>
      </div>
    </div>
  </div>
</template>

// src/components/composed/kpi-card.tsx
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import type { LucideIcon } from "lucide-react";

interface KPICardProps {
  title: string;
  value: string | number;
  description?: string;
  icon?: LucideIcon;
  trend?: "up" | "down" | "neutral";
  trendValue?: string;
  loading?: boolean;
  className?: string;
}

export function KPICard({
  title,
  value,
  description,
  icon: Icon,
  trend,
  trendValue,
  loading,
  className,
}: KPICardProps) {
  if (loading) {
    return (
      <Card className={className}>
        <CardContent className="p-6">
          <Skeleton className="mb-2 h-4 w-24" />
          <Skeleton className="mb-1 h-8 w-16" />
          <Skeleton className="h-3 w-32" />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className={className}>
      <CardContent className="p-6">
        <div className="flex items-center justify-between">
          <p className="text-sm font-medium text-[hsl(var(--muted-foreground))]">
            {title}
          </p>
          {Icon && (
            <Icon className="size-4 text-[hsl(var(--muted-foreground))]" />
          )}
        </div>
        <div className="mt-2 flex items-baseline gap-2">
          <p className="text-2xl font-bold">{value}</p>
          {trend && trendValue && (
            <span
              className={cn(
                "text-xs font-medium",
                trend === "up" && "text-[hsl(var(--success))]",
                trend === "down" && "text-[hsl(var(--destructive))]",
                trend === "neutral" && "text-[hsl(var(--muted-foreground))]",
              )}
            >
              {trendValue}
            </span>
          )}
        </div>
        {description && (
          <p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">
            {description}
          </p>
        )}
      </CardContent>
    </Card>
  );
}
