// src/routes/_app/pipeline/porep.tsx
import { createFileRoute } from "@tanstack/react-router";
import type { ColumnDef } from "@tanstack/react-table";
import { RotateCcw } from "lucide-react";
import { useMemo, useState } from "react";
import { KPICard } from "@/components/composed/kpi-card";
import { StatusBadge } from "@/components/composed/status-badge";
import { DataTable } from "@/components/table/data-table";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useCurioRpc, useCurioRpcMutation } from "@/hooks/use-curio-query";
import type { PorepPipelineSummary, SectorListEntry } from "@/types/pipeline";

export const Route = createFileRoute("/_app/pipeline/porep")({
  component: PoRepPage,
});

const sectorColumns: ColumnDef<SectorListEntry>[] = [
  { accessorKey: "SectorNumber", header: "Sector" },
  { accessorKey: "Address", header: "Miner" },
  { accessorKey: "CreateTime", header: "Created" },
  {
    id: "stage",
    header: "Stage",
    cell: ({ row }) => {
      const s = row.original;
      if (s.Failed) return <StatusBadge status="failed" label="Failed" />;
      if (s.AfterCommitMsgSuccess)
        return <StatusBadge status="done" label="Done" />;
      if (s.AfterCommitMsg)
        return <StatusBadge status="running" label="CommitMsg" />;
      if (s.AfterPoRep) return <StatusBadge status="running" label="PoRep" />;
      if (s.AfterPrecommitMsgSuccess)
        return <StatusBadge status="running" label="WaitSeed" />;
      if (s.AfterPrecommitMsg)
        return <StatusBadge status="running" label="PreCommit" />;
      if (s.AfterTreeR) return <StatusBadge status="running" label="Trees" />;
      if (s.AfterSDR) return <StatusBadge status="running" label="SDR" />;
      return <StatusBadge status="pending" label="Pending" />;
    },
  },
  {
    accessorKey: "FailedReason",
    header: "Error",
    cell: ({ row }) =>
      row.original.Failed ? (
        <span
          className="max-w-xs truncate text-xs text-[hsl(var(--destructive))]"
          title={row.original.FailedReason}
        >
          {row.original.FailedReason}
        </span>
      ) : (
        "—"
      ),
  },
];

function PoRepPage() {
  const { data: summaryData, isLoading: summaryLoading } = useCurioRpc<
    PorepPipelineSummary[]
  >("PipelinePorepSectors", [], { refetchInterval: 30_000 });

  const { data: sectorsData, isLoading: sectorsLoading } = useCurioRpc<
    SectorListEntry[]
  >("PipelineStatsSDR", [], { refetchInterval: 30_000 });

  const restartAllMutation = useCurioRpcMutation("PipelinePorepRestartAll", {
    invalidateKeys: [
      ["curio", "PipelinePorepSectors"],
      ["curio", "PipelineStatsSDR"],
    ],
  });

  const [confirmRestart, setConfirmRestart] = useState(false);

  const totals = useMemo(() => {
    if (!summaryData) return null;
    return summaryData.reduce(
      (acc, s) => ({
        sdr: acc.sdr + s.CountSDR,
        trees: acc.trees + s.CountTrees,
        precommit: acc.precommit + s.CountPrecommitMsg,
        waitSeed: acc.waitSeed + s.CountWaitSeed,
        porep: acc.porep + s.CountPoRep,
        commit: acc.commit + s.CountCommitMsg,
        done: acc.done + s.CountDone,
        failed: acc.failed + s.CountFailed,
      }),
      {
        sdr: 0,
        trees: 0,
        precommit: 0,
        waitSeed: 0,
        porep: 0,
        commit: 0,
        done: 0,
        failed: 0,
      },
    );
  }, [summaryData]);

  if (summaryLoading && !summaryData) {
    return (
      <div className="grid gap-4 sm:grid-cols-4">
        {Array.from({ length: 8 }).map((_, i) => (
          <Skeleton key={i} className="h-24" />
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold">PoRep Pipeline</h2>
        {confirmRestart ? (
          <div className="flex items-center gap-2">
            <span className="text-xs text-[hsl(var(--destructive))]">
              Restart all failed PoRep tasks?
            </span>
            <Button
              size="sm"
              variant="destructive"
              onClick={() => {
                restartAllMutation.mutate([]);
                setConfirmRestart(false);
              }}
              disabled={restartAllMutation.isPending}
            >
              Yes
            </Button>
            <Button
              size="sm"
              variant="ghost"
              onClick={() => setConfirmRestart(false)}
            >
              No
            </Button>
          </div>
        ) : (
          <Button
            size="sm"
            variant="outline"
            onClick={() => setConfirmRestart(true)}
          >
            <RotateCcw className="mr-1 size-3" /> Restart All Failed
          </Button>
        )}
      </div>
      {totals && (
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-8">
          <KPICard label="SDR" value={totals.sdr} />
          <KPICard label="Trees" value={totals.trees} />
          <KPICard label="PreCommit" value={totals.precommit} />
          <KPICard label="WaitSeed" value={totals.waitSeed} />
          <KPICard label="PoRep" value={totals.porep} />
          <KPICard label="Commit" value={totals.commit} />
          <KPICard label="Done" value={totals.done} />
          <KPICard label="Failed" value={totals.failed} />
        </div>
      )}

      {summaryData && summaryData.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Pipeline by Actor</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-[hsl(var(--border))] text-left text-[hsl(var(--muted-foreground))]">
                    <th className="px-3 py-2">Actor</th>
                    <th className="px-3 py-2">SDR</th>
                    <th className="px-3 py-2">Trees</th>
                    <th className="px-3 py-2">PreCommit</th>
                    <th className="px-3 py-2">WaitSeed</th>
                    <th className="px-3 py-2">PoRep</th>
                    <th className="px-3 py-2">Commit</th>
                    <th className="px-3 py-2">Done</th>
                    <th className="px-3 py-2">Failed</th>
                  </tr>
                </thead>
                <tbody>
                  {summaryData.map((s) => (
                    <tr
                      key={s.Actor}
                      className="border-b border-[hsl(var(--border))] last:border-0"
                    >
                      <td className="px-3 py-2 font-mono">{s.Actor}</td>
                      <td className="px-3 py-2">{s.CountSDR}</td>
                      <td className="px-3 py-2">{s.CountTrees}</td>
                      <td className="px-3 py-2">{s.CountPrecommitMsg}</td>
                      <td className="px-3 py-2">{s.CountWaitSeed}</td>
                      <td className="px-3 py-2">{s.CountPoRep}</td>
                      <td className="px-3 py-2">{s.CountCommitMsg}</td>
                      <td className="px-3 py-2">{s.CountDone}</td>
                      <td className="px-3 py-2">{s.CountFailed || "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Active Sectors</CardTitle>
        </CardHeader>
        <CardContent>
          <DataTable
            columns={sectorColumns}
            data={sectorsData ?? []}
            loading={sectorsLoading}
            searchable
            searchPlaceholder="Search sectors..."
            searchColumn="Address"
            emptyMessage="No active pipeline sectors"
          />
        </CardContent>
      </Card>
    </div>
  );
}

// src/pages/pipeline/porep.vue
<!-- eslint-disable vue/multi-word-component-names -->
<route>
{
  "meta": {
    "title": "PoRep Pipeline"
  }
}
</route>

<template>
  <PipelineLayout current-tab="porep">
    <div class="space-y-4">
      <!-- Integrated Header Dashboard -->
      <div class="bg-base-100 rounded-lg p-4 shadow">
        <!-- Title Row with Quick Stats -->
        <div class="flex items-start justify-between">
          <div class="flex items-center gap-6">
            <div>
              <h2 class="text-base-content text-xl font-semibold">
                PoRep Pipeline
              </h2>
            </div>
            <!-- Inline Stats -->
            <div class="flex items-center gap-4 border-l pl-6">
              <div class="text-center">
                <div class="text-base-content text-lg font-bold">
                  {{ totalSectors }}
                </div>
                <div class="text-base-content/60 text-xs">Total</div>
              </div>
              <div class="text-center">
                <div class="text-info text-lg font-bold">
                  {{ activeSectors }}
                </div>
                <div class="text-base-content/60 text-xs">Active</div>
              </div>
              <div class="text-center">
                <div class="text-success text-lg font-bold">
                  {{ completedSectors }}
                </div>
                <div class="text-base-content/60 text-xs">Completed</div>
              </div>
              <div class="text-center">
                <div
                  class="text-lg font-bold"
                  :class="failedCount > 0 ? 'text-error' : 'text-base-content'"
                >
                  {{ failedCount }}
                </div>
                <div class="text-base-content/60 text-xs">Failed</div>
              </div>
            </div>
          </div>
          <!-- Action Buttons -->
          <div class="flex gap-2">
            <button
              :disabled="isRefreshingDashboard"
              class="btn btn-outline btn-sm"
              @click="refreshDashboard"
            >
              <ArrowPathIcon
                class="h-4 w-4"
                :class="{ 'animate-spin': isRefreshingDashboard }"
              />
              Refresh
            </button>
            <button
              :disabled="isRestarting"
              class="btn btn-warning btn-sm"
              @click="handleRestartAll"
            >
              <ExclamationTriangleIcon
                class="h-4 w-4"
                :class="{ 'animate-spin': isRestarting }"
              />
              Restart All Failed
            </button>
          </div>
        </div>

        <!-- Pipeline Breakdown Table -->
        <div class="mt-4 border-t pt-3">
          <div
            v-if="porepSummary.loading.value || porepStats.loading.value"
            class="flex justify-center py-2"
          >
            <span class="loading loading-spinner loading-sm"></span>
          </div>
          <div v-else-if="porepSummary.data.value" class="overflow-x-auto">
            <table class="table w-full">
              <thead>
                <tr class="text-base-content/60">
                  <th>Actor</th>
                  <th class="text-center">SDR</th>
                  <th class="text-center">Trees</th>
                  <th class="text-center">PreCommit</th>
                  <th class="text-center">WaitSeed</th>
                  <th class="text-center">PoRep</th>
                  <th class="text-center">Commit</th>
                  <th class="text-center">Done</th>
                  <th class="text-center">Failed</th>
                  <th class="text-right">Total</th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="summary in porepSummary.data.value"
                  :key="summary.Actor"
                  class="hover"
                >
                  <td class="font-medium">{{ summary.Actor }}</td>
                  <td class="text-center">
                    <span
                      v-if="summary.CountSDR > 0"
                      class="text-info font-medium"
                      >{{ summary.CountSDR }}</span
                    >
                    <span v-else class="text-base-content/30">-</span>
                  </td>
                  <td class="text-center">
                    <span
                      v-if="summary.CountTrees > 0"
                      class="text-info font-medium"
                      >{{ summary.CountTrees }}</span
                    >
                    <span v-else class="text-base-content/30">-</span>
                  </td>
                  <td class="text-center">
                    <span
                      v-if="summary.CountPrecommitMsg > 0"
                      class="text-warning font-medium"
                      >{{ summary.CountPrecommitMsg }}</span
                    >
                    <span v-else class="text-base-content/30">-</span>
                  </td>
                  <td class="text-center">
                    <span
                      v-if="summary.CountWaitSeed > 0"
                      class="text-warning font-medium"
                      >{{ summary.CountWaitSeed }}</span
                    >
                    <span v-else class="text-base-content/30">-</span>
                  </td>
                  <td class="text-center">
                    <span
                      v-if="summary.CountPoRep > 0"
                      class="text-info font-medium"
                      >{{ summary.CountPoRep }}</span
                    >
                    <span v-else class="text-base-content/30">-</span>
                  </td>
                  <td class="text-center">
                    <span
                      v-if="summary.CountCommitMsg > 0"
                      class="text-warning font-medium"
                      >{{ summary.CountCommitMsg }}</span
                    >
                    <span v-else class="text-base-content/30">-</span>
                  </td>
                  <td class="text-center">
                    <span
                      v-if="summary.CountDone > 0"
                      class="text-success font-medium"
                      >{{ summary.CountDone }}</span
                    >
                    <span v-else class="text-base-content/30">-</span>
                  </td>
                  <td class="text-center">
                    <span
                      v-if="summary.CountFailed > 0"
                      class="text-error font-medium"
                      >{{ summary.CountFailed }}</span
                    >
                    <span v-else class="text-base-content/30">-</span>
                  </td>
                  <td class="text-right font-medium">
                    {{ getTotalCount(summary) }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Sectors Table -->
      <SectionCard title="Active Sectors" :icon="CogIcon">
        <template #actions>
          <button
            :disabled="porepSectors.loading.value"
            class="btn btn-outline btn-sm"
            @click="porepSectors.refresh"
          >
            <ArrowPathIcon
              class="h-4 w-4"
              :class="{ 'animate-spin': porepSectors.loading.value }"
            />
            Refresh
          </button>
        </template>
        <PoRepSectorsTable
          :sectors="porepSectors.data.value || []"
          :loading="porepSectors.loading.value"
          :error="porepSectors.error.value"
          :on-refresh="porepSectors.refresh"
        />
      </SectionCard>
    </div>
  </PipelineLayout>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import {
  ArrowPathIcon,
  ExclamationTriangleIcon,
  CogIcon,
} from "@heroicons/vue/24/outline";

import SectionCard from "@/components/ui/SectionCard.vue";
import PoRepSectorsTable from "./components/PoRepSectorsTable.vue";
import PipelineLayout from "./components/PipelineLayout.vue";
import { useCachedQuery } from "@/composables/useCachedQuery";
import { useCurioQuery } from "@/composables/useCurioQuery";
import { usePageTitle } from "@/composables/usePageTitle";
import type {
  PorepPipelineSummary,
  SectorListEntry,
  PipelineStats,
} from "@/types/pipeline";

// Direct queries for each data need
const porepSectors = useCachedQuery<SectorListEntry[]>(
  "PipelinePorepSectors",
  [],
  {
    pollingInterval: 30000,
  },
);

const porepSummary = useCachedQuery<PorepPipelineSummary[]>(
  "PorepPipelineSummary",
  [],
  {
    pollingInterval: 30000,
  },
);

const porepStats = useCachedQuery<PipelineStats>("PipelineStatsSDR", [], {
  pollingInterval: 30000,
});

// Action functions
const { pipelinePorepRestartAll } = useCurioQuery();

const restartPorepPipeline = async () => {
  try {
    await pipelinePorepRestartAll();
    await Promise.all([
      porepSectors.refresh(),
      porepSummary.refresh(),
      porepStats.refresh(),
    ]);
    return { success: true };
  } catch (error) {
    console.error("Failed to restart PoRep pipeline:", error);
    return { success: false, error: error as Error };
  }
};

const getTotalCount = (summary: PorepPipelineSummary): number => {
  return (
    summary.CountSDR +
    summary.CountTrees +
    summary.CountPrecommitMsg +
    summary.CountWaitSeed +
    summary.CountPoRep +
    summary.CountCommitMsg +
    summary.CountDone +
    summary.CountFailed
  );
};

const isRestarting = ref(false);
const isRefreshingDashboard = ref(false);

// Calculate all statistics from PorepPipelineSummary data for consistency with table
const totalSectors = computed(() => {
  if (!porepSummary.data.value) return 0;
  return porepSummary.data.value.reduce((total, summary) => {
    return total + getTotalCount(summary);
  }, 0);
});

const activeSectors = computed(() => {
  if (!porepSummary.data.value) return 0;
  // Active sectors are those in pipeline stages (SDR, Trees, PreCommit, WaitSeed, PoRep, Commit)
  return porepSummary.data.value.reduce((total, summary) => {
    return (
      total +
      summary.CountSDR +
      summary.CountTrees +
      summary.CountPrecommitMsg +
      summary.CountWaitSeed +
      summary.CountPoRep +
      summary.CountCommitMsg
    );
  }, 0);
});

const completedSectors = computed(() => {
  if (!porepSummary.data.value) return 0;
  // Completed sectors are those marked as Done
  return porepSummary.data.value.reduce((total, summary) => {
    return total + summary.CountDone;
  }, 0);
});

const failedCount = computed(() => {
  if (!porepSummary.data.value) return 0;
  // Failed sectors from all actors
  return porepSummary.data.value.reduce((total, summary) => {
    return total + summary.CountFailed;
  }, 0);
});

const { updateTitle } = usePageTitle();

// Update title with active sector count
const dynamicTitle = computed(() => {
  const loading = porepSummary.loading.value || porepStats.loading.value;
  const error = porepSummary.error.value || porepStats.error.value;

  if (loading && !porepSummary.data.value && !porepStats.data.value) {
    return "Loading...";
  }
  if (error && !porepSummary.data.value && !porepStats.data.value) {
    return "Error";
  }

  return `PoRep Pipeline (${activeSectors.value} active)`;
});

updateTitle(dynamicTitle);

const refreshDashboard = async () => {
  isRefreshingDashboard.value = true;
  try {
    await Promise.all([porepSummary.refresh(), porepStats.refresh()]);
  } finally {
    isRefreshingDashboard.value = false;
  }
};

const refreshAllData = async () => {
  await Promise.all([
    porepSummary.refresh(),
    porepStats.refresh(),
    porepSectors.refresh(),
  ]);
};

const handleRestartAll = async () => {
  isRestarting.value = true;
  try {
    await restartPorepPipeline();
    await refreshAllData();
  } finally {
    isRestarting.value = false;
  }
};
</script>
