// src/pages/overview/components/TaskCounts.vue
<script setup lang="ts">
import { computed } from "vue";
import { useCachedQuery } from "@/composables/useCachedQuery";
import { CheckCircleIcon, XCircleIcon } from "@heroicons/vue/24/outline";
import DataTable from "@/components/ui/DataTable.vue";
import type { HarmonyTaskStat, TaskStatWithPercentage } from "@/types/cluster";

const {
  data: rawData,
  loading,
  error,
  hasData,
} = useCachedQuery<HarmonyTaskStat[]>("HarmonyTaskStats", [], {
  pollingInterval: 30000,
});

const isInitialLoading = computed(() => loading.value && !hasData.value);
const processedData = computed<TaskStatWithPercentage[]>(() => {
  if (rawData.value && rawData.value.length > 0) {
    return rawData.value.map((task) => ({
      ...task,
      FailedPercentage:
        task.FalseCount > 0
          ? `${((task.FalseCount / task.TotalCount) * 100).toFixed(2)}%`
          : "0%",
      isError: task.FalseCount > task.TrueCount && task.TrueCount === 0,
    }));
  }
  return [];
});

const getSuccessRate = (task: TaskStatWithPercentage): number => {
  return task.TotalCount > 0 ? (task.TrueCount / task.TotalCount) * 100 : 0;
};

const getStatusBadge = (task: TaskStatWithPercentage) => {
  if (task.isError) {
    return { class: "badge-error", icon: XCircleIcon };
  }
  if (task.FalseCount === 0) {
    return { class: "badge-success", icon: CheckCircleIcon };
  }
  return { class: "badge-warning", icon: null };
};
</script>

<template>
  <div class="space-y-4">
    <DataTable :compact="true">
      <thead>
        <tr>
          <th class="w-2/5">Task Name</th>
          <th class="w-2/5">Success Rate</th>
          <th class="w-1/5 text-center">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="task in processedData"
          :key="task.Name"
          :class="{ 'bg-error/10': task.isError }"
        >
          <td class="truncate font-medium">
            <span
              :class="{ 'text-error': task.isError }"
              :title="task.Name"
              class="block truncate"
            >
              {{ task.Name }}
            </span>
          </td>

          <td>
            <div class="flex items-center gap-3">
              <span class="min-w-[3rem] text-sm font-medium">
                {{ getSuccessRate(task).toFixed(1) }}%
              </span>
              <progress
                class="progress progress-sm flex-1"
                :class="
                  task.isError
                    ? 'progress-error'
                    : task.FalseCount === 0
                      ? 'progress-success'
                      : 'progress-warning'
                "
                :value="getSuccessRate(task)"
                max="100"
              ></progress>
              <span class="text-base-content/50 min-w-[4rem] text-xs">
                {{ task.TrueCount }}/{{ task.TotalCount }}
              </span>
            </div>
          </td>

          <td class="text-center">
            <div class="badge badge-sm" :class="getStatusBadge(task).class">
              <component
                :is="getStatusBadge(task).icon"
                v-if="getStatusBadge(task).icon"
                class="mr-1 size-3"
              />
              {{
                task.isError
                  ? "Error"
                  : task.FalseCount === 0
                    ? "Healthy"
                    : "Warning"
              }}
            </div>
          </td>
        </tr>
      </tbody>
    </DataTable>

    <div v-if="isInitialLoading" class="text-base-content/60 py-8 text-center">
      <div class="loading loading-spinner loading-lg mx-auto mb-4"></div>
      Loading task statistics...
    </div>

    <div v-else-if="error" class="text-error py-8 text-center">
      <div class="mb-2 text-lg">📊 Task Stats Error</div>
      <div class="text-sm">{{ error.message }}</div>
    </div>

    <div
      v-else-if="processedData.length === 0 && !loading"
      class="text-base-content/60 py-8 text-center"
    >
      <div class="mb-2 text-4xl">📊</div>
      <div>No task statistics available</div>
    </div>
  </div>
</template>

// src/routes/_app/overview/-components/task-counts.tsx
import { BarChart3 } from "lucide-react";
import { SectionCard } from "@/components/composed/section-card";
import { Skeleton } from "@/components/ui/skeleton";
import type { HarmonyTaskStat } from "@/types/cluster";

interface TaskCountsProps {
  data: HarmonyTaskStat[];
  loading: boolean;
}

export function TaskCounts({ data, loading }: TaskCountsProps) {
  if (loading) {
    return (
      <SectionCard title="Task Statistics" icon={BarChart3}>
        <div className="space-y-3">
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className="h-8 w-full" />
          ))}
        </div>
      </SectionCard>
    );
  }

  if (!data.length) {
    return (
      <SectionCard title="Task Statistics" icon={BarChart3}>
        <p className="text-sm text-muted-foreground">
          No task statistics available
        </p>
      </SectionCard>
    );
  }

  const sorted = [...data].sort((a, b) => b.TotalCount - a.TotalCount);

  return (
    <SectionCard title="Task Statistics" icon={BarChart3}>
      <div className="space-y-2">
        {sorted.slice(0, 10).map((stat) => {
          const successRate =
            stat.TotalCount === 0
              ? 0
              : (stat.TrueCount / stat.TotalCount) * 100;

          return (
            <div
              key={stat.Name}
              className="flex items-center justify-between rounded-md border border-border px-3 py-2 text-sm"
            >
              <span className="font-medium">{stat.Name}</span>
              <div className="flex items-center gap-3 text-xs text-muted-foreground">
                <span>{stat.TotalCount} total</span>
                <span
                  className={
                    successRate >= 95
                      ? "text-success"
                      : successRate >= 80
                        ? "text-warning"
                        : "text-destructive"
                  }
                >
                  {successRate.toFixed(1)}%
                </span>
              </div>
            </div>
          );
        })}
      </div>
    </SectionCard>
  );
}
