// src/routes/_app/overview/-components/dashboard-hero.tsx
import { RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import type { HeroCard } from "@/hooks/use-dashboard-summary";
import { cn } from "@/lib/utils";

const statusDotColors: Record<string, string> = {
  success: "bg-success",
  warning: "bg-warning",
  info: "bg-info",
  accent: "bg-primary",
};

interface DashboardHeroProps {
  cards: HeroCard[];
  loading: boolean;
  onRefresh: () => void;
}

export function DashboardHero({
  cards,
  loading,
  onRefresh,
}: DashboardHeroProps) {
  if (loading && cards.every((c) => c.value === "0" || c.value === "0/0")) {
    return (
      <section className="flex flex-col gap-4">
        <div className="flex items-center justify-between">
          <Skeleton className="h-8 w-48" />
          <Skeleton className="h-8 w-20" />
        </div>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
          {Array.from({ length: 6 }).map((_, i) => (
            <Card key={i} size="sm">
              <CardHeader>
                <Skeleton className="h-3 w-20" />
              </CardHeader>
              <CardContent className="flex flex-col gap-1">
                <Skeleton className="h-7 w-14" />
                <Skeleton className="h-3 w-28" />
              </CardContent>
            </Card>
          ))}
        </div>
      </section>
    );
  }

  return (
    <section className="flex flex-col gap-3">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <h1 className="text-2xl font-semibold tracking-tight">
            Cluster Overview
          </h1>
        </div>
        <Button variant="outline" size="sm" onClick={onRefresh}>
          <RefreshCw data-icon="inline-start" />
          Refresh
        </Button>
      </div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
        {cards.map((card) => (
          <Card key={card.id} size="sm" className="min-w-0">
            <CardHeader>
              <CardTitle className="truncate text-muted-foreground">
                {card.label}
              </CardTitle>
              <CardAction>
                <span
                  className={cn(
                    "block size-2 rounded-full",
                    statusDotColors[card.status],
                  )}
                />
              </CardAction>
            </CardHeader>
            <CardContent>
              <div className="truncate text-xl font-semibold tabular-nums leading-tight">
                {card.value}
              </div>
              <CardDescription className="truncate">
                {card.subtitle}
              </CardDescription>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  );
}

// src/pages/overview/components/DashboardHero.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { Component } from "vue";
import {
  ArrowPathIcon,
  BoltIcon,
  CircleStackIcon,
  ServerStackIcon,
  UserGroupIcon,
} from "@heroicons/vue/24/outline";
import KPICard from "@/components/ui/KPICard.vue";
import type {
  DashboardMetrics,
  DashboardStatus,
  HeroSnapshot,
} from "../composables/useDashboardSummary";

type IconColor =
  | "primary"
  | "secondary"
  | "accent"
  | "info"
  | "success"
  | "warning"
  | "error"
  | "neutral"
  | "muted";

type HeroCardPreset = "machines" | "tasks" | "storage" | "actors";

interface Props {
  metrics: DashboardMetrics;
  status: DashboardStatus;
  lastUpdatedLabel: string;
  formattedTaskSuccessRate: string;
  machineHealthLabel: string;
  runningTasksLabel: string;
  loading: boolean;
  loadingSkeleton: boolean;
  heroSnapshot: HeroSnapshot;
  onRefresh?: () => Promise<void> | void;
}

const props = defineProps<Props>();

const refreshing = ref(false);

const cardIconMap: Record<
  HeroCardPreset,
  { icon: Component; fallbackColor: IconColor }
> = {
  machines: { icon: ServerStackIcon, fallbackColor: "neutral" },
  tasks: { icon: BoltIcon, fallbackColor: "neutral" },
  storage: { icon: CircleStackIcon, fallbackColor: "neutral" },
  actors: { icon: UserGroupIcon, fallbackColor: "neutral" },
};

const statusColorMap: Record<
  HeroSnapshot["cards"][number]["status"],
  IconColor
> = {
  success: "success",
  warning: "warning",
  info: "info",
  accent: "accent",
};

const cards = computed(() =>
  props.heroSnapshot.cards.map((card) => {
    const preset = cardIconMap[card.id];
    const iconColor = (statusColorMap[card.status] ??
      preset.fallbackColor) as IconColor;

    return {
      ...card,
      icon: preset.icon,
      iconColor,
    };
  }),
);

const handleRefresh = async () => {
  if (refreshing.value || !props.onRefresh) return;
  refreshing.value = true;
  try {
    await props.onRefresh();
  } finally {
    refreshing.value = false;
  }
};
</script>

<template>
  <div class="bg-base-100 border-base-300 rounded-2xl border p-5 shadow-sm">
    <div
      class="border-base-300 flex flex-col gap-3 border-b pb-4 md:flex-row md:items-center md:justify-between"
    >
      <div class="flex items-center gap-3">
        <span class="badge" :class="props.status.variant">
          {{ props.status.label }}
        </span>
        <span class="text-base-content text-sm font-semibold">
          Cluster Overview
        </span>
      </div>
      <div
        class="text-base-content/60 flex flex-wrap items-center gap-3 text-xs"
      >
        <span>Updated {{ props.lastUpdatedLabel }}</span>
        <span v-if="props.status.issues > 0" class="text-warning">
          {{ props.status.endpointIssues }} endpoint alerts ·
          {{ props.status.offlineMachines }} machines offline
        </span>
        <button
          class="btn btn-outline btn-xs"
          :disabled="props.loading || refreshing || !props.onRefresh"
          @click="handleRefresh"
        >
          <ArrowPathIcon
            class="size-4"
            :class="{ 'animate-spin': props.loading || refreshing }"
          />
          Refresh
        </button>
      </div>
    </div>

    <div v-if="props.loadingSkeleton" class="mt-4 grid gap-3 md:grid-cols-2">
      <div v-for="index in 4" :key="`skeleton-${index}`" class="animate-pulse">
        <div class="bg-base-200 h-24 rounded-xl" />
      </div>
    </div>

    <div v-else class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      <KPICard
        v-for="card in cards"
        :key="card.id"
        :label="card.label"
        :value="card.value"
        :subtitle="card.subtitle"
        :icon="card.icon"
        :icon-color="card.iconColor"
      />
    </div>
  </div>
</template>
*** End Patch
