// src/pages/config/index.vue
<route>
{
  "meta": {
    "title": "Configuration"
  }
}
</route>

<script setup lang="ts">
import { computed, ref } from "vue";
import { InformationCircleIcon } from "@heroicons/vue/24/outline";

import ConfigLayerList from "./components/ConfigLayerList.vue";
import ConfigLayerEditor from "./components/ConfigLayerEditor.vue";
import ConfigTomlPreview from "./components/ConfigTomlPreview.vue";
import BaseModal from "@/components/ui/BaseModal.vue";
import { useConfigLayers } from "@/composables/useConfigLayers";
import { useConfigDefinitions } from "@/composables/useConfigDefinitions";
import { useConfigEditor } from "@/composables/useConfigEditor";
import { createConfigLayer } from "@/services/config-api";

const layers = useConfigLayers();
const definitions = useConfigDefinitions();

const editor = useConfigEditor({
  selectedLayer: layers.selectedLayer,
  defaults: definitions.defaults,
  schema: definitions.schema,
});

const sections = computed(() => {
  const groups = editor.groupedRows.value;
  return Array.from(groups.entries()).map(([key, rows]) => ({
    key,
    label: rows[0]?.groupLabel ?? key,
    rows,
  }));
});

interface StatusMessage {
  type: "success" | "error";
  text: string;
}

const status = ref<StatusMessage | null>(null);
const showCreateModal = ref(false);
const newLayerName = ref("");
const createError = ref("");
const creatingLayer = ref(false);

const loadError = computed(() => {
  return (
    definitions.error.value ?? layers.error.value ?? editor.error.value ?? null
  );
});

const layerListError = computed(() => {
  if (definitions.error.value) {
    return null;
  }
  return layers.error.value;
});

const loadErrorMessage = computed(() => loadError.value?.message ?? "");
const hasLoadError = computed(() => Boolean(loadError.value));

const setStatus = (payload: StatusMessage | null) => {
  status.value = payload;
  if (payload) {
    window.setTimeout(() => {
      if (status.value === payload) {
        status.value = null;
      }
    }, 4000);
  }
};

const openCreateModal = () => {
  newLayerName.value = "";
  createError.value = "";
  showCreateModal.value = true;
};

const closeCreateModal = () => {
  showCreateModal.value = false;
};

const handleCreateLayer = async () => {
  const trimmed = newLayerName.value.trim();
  if (!trimmed.length) {
    createError.value = "Layer name cannot be empty.";
    return;
  }

  creatingLayer.value = true;
  createError.value = "";

  try {
    await createConfigLayer(trimmed);
    await layers.refresh();
    layers.selectLayer(trimmed);
    showCreateModal.value = false;
    setStatus({
      type: "success",
      text: `Layer "${trimmed}" created successfully.`,
    });
  } catch (err) {
    createError.value = (err as Error).message ?? "Failed to create layer.";
  } finally {
    creatingLayer.value = false;
  }
};

const handleSave = async () => {
  try {
    await editor.save();
    setStatus({
      type: "success",
      text: "Configuration saved.",
    });
  } catch (err) {
    setStatus({
      type: "error",
      text: (err as Error).message ?? "Failed to save configuration.",
    });
  }
};

const handleOverrideToggle = (payload: {
  path: string[];
  enabled: boolean;
  fallback: unknown;
}) => {
  if (payload.enabled) {
    editor.updateFieldValue(payload.path, payload.fallback);
  } else {
    editor.disableFieldOverride(payload.path);
  }
};
</script>

<template>
  <div class="space-y-6 p-6">
    <div
      v-if="status"
      :class="[
        'mb-4 flex items-start gap-2 rounded-lg border px-4 py-3 text-sm',
        status.type === 'success'
          ? 'border-success/40 bg-success/10 text-success'
          : 'border-error/40 bg-error/10 text-error',
      ]"
    >
      <InformationCircleIcon class="size-5 shrink-0" />
      <span>{{ status.text }}</span>
    </div>

    <div
      v-if="hasLoadError"
      class="border-error/40 bg-error/10 text-error mb-4 flex items-start gap-2 rounded-lg border px-4 py-3 text-sm"
    >
      <InformationCircleIcon class="size-5 shrink-0" />
      <span>{{ loadErrorMessage }}</span>
    </div>

    <div
      class="grid gap-6 lg:grid-cols-[minmax(320px,1.1fr)_minmax(560px,1.6fr)_minmax(320px,1.1fr)] xl:grid-cols-[minmax(340px,1.15fr)_minmax(640px,1.65fr)_minmax(340px,1.15fr)] 2xl:grid-cols-[minmax(360px,1.2fr)_minmax(720px,1.7fr)_minmax(360px,1.2fr)]"
    >
      <ConfigLayerList
        :layers="layers.layers.value"
        :loading="layers.loading.value"
        :error="layerListError"
        :selected-layer="layers.selectedLayer.value"
        :disable-create="definitions.loading.value || hasLoadError"
        @update:selected="layers.selectLayer"
        @refresh="layers.refresh"
        @create="openCreateModal"
      />

      <ConfigLayerEditor
        :sections="sections"
        :loading="editor.loading.value || definitions.loading.value"
        :error="editor.error.value"
        :selected-layer="layers.selectedLayer.value"
        :is-default-layer="editor.isDefaultLayer.value"
        :dirty="editor.dirty.value"
        :saving="editor.saving.value"
        @update="({ path, value }) => editor.updateFieldValue(path, value)"
        @toggle="handleOverrideToggle"
        @reset-row="({ path }) => editor.disableFieldOverride(path)"
        @reset-all="editor.reset"
        @save="handleSave"
      />

      <ConfigTomlPreview
        :toml="editor.tomlPreview.value"
        :loading="definitions.loading.value || editor.loading.value"
        :selected-layer="layers.selectedLayer.value"
        :dirty="editor.dirty.value"
      />
    </div>

    <BaseModal
      :open="showCreateModal"
      title="Create Configuration Layer"
      size="sm"
      @close="closeCreateModal"
    >
      <form
        id="create-layer-form"
        class="flex flex-col gap-4 py-4"
        @submit.prevent="handleCreateLayer"
      >
        <label class="form-control w-full">
          <span class="label">
            <span class="label-text font-medium">Layer Name</span>
            <span class="label-text-alt">
              Unique identifier without spaces.
            </span>
          </span>
          <input
            v-model="newLayerName"
            type="text"
            class="input input-bordered w-full"
            placeholder="e.g. sealing-cluster"
            :disabled="creatingLayer"
            autofocus
          />
        </label>

        <p v-if="createError" class="text-error text-sm">
          {{ createError }}
        </p>
      </form>

      <template #footer>
        <div class="flex items-center justify-end gap-2">
          <button
            type="button"
            class="btn btn-ghost"
            :disabled="creatingLayer"
            @click="closeCreateModal"
          >
            Cancel
          </button>
          <button
            type="submit"
            class="btn btn-primary"
            :disabled="creatingLayer"
            form="create-layer-form"
          >
            <span
              v-if="creatingLayer"
              class="loading loading-spinner loading-xs"
            ></span>
            Create Layer
          </button>
        </div>
      </template>
    </BaseModal>
  </div>
</template>

// src/routes/_app/config/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { useState, useCallback } from "react";
import { usePageTitle } from "@/hooks/use-page-title";
import { useCurioRest } from "@/hooks/use-curio-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Settings, Plus, Save, FileText } from "lucide-react";
import { useCurioApi } from "@/contexts/curio-api-context";
import {
  fetchConfigLayer,
  saveConfigLayer,
  createConfigLayer,
} from "@/services/config-api";
import type { ConfigTopologyEntry } from "@/types/config";

export const Route = createFileRoute("/_app/config/")({
  component: ConfigPage,
});

function ConfigPage() {
  usePageTitle("Configuration");
  const api = useCurioApi();

  const { data: layers, isLoading: layersLoading, refetch: refetchLayers } =
    useCurioRest<string[]>("/api/config/layers", { refetchInterval: 60_000 });

  const { data: topology } = useCurioRest<ConfigTopologyEntry[]>(
    "/api/config/topo",
    { refetchInterval: 60_000 },
  );

  const [selectedLayer, setSelectedLayer] = useState<string | null>(null);
  const [layerContent, setLayerContent] = useState<string>("");
  const [loadingLayer, setLoadingLayer] = useState(false);
  const [saving, setSaving] = useState(false);
  const [statusMsg, setStatusMsg] = useState<string | null>(null);
  const [newLayerName, setNewLayerName] = useState("");
  const [showCreate, setShowCreate] = useState(false);

  const loadLayer = useCallback(
    async (name: string) => {
      setSelectedLayer(name);
      setLoadingLayer(true);
      setStatusMsg(null);
      try {
        const data = await fetchConfigLayer(api, name);
        setLayerContent(JSON.stringify(data, null, 2));
      } catch (err) {
        setStatusMsg(`Error loading layer: ${err}`);
      } finally {
        setLoadingLayer(false);
      }
    },
    [api],
  );

  const handleSave = useCallback(async () => {
    if (!selectedLayer) return;
    setSaving(true);
    setStatusMsg(null);
    try {
      const payload = JSON.parse(layerContent);
      await saveConfigLayer(api, selectedLayer, payload);
      setStatusMsg("Saved successfully");
    } catch (err) {
      setStatusMsg(`Error saving: ${err}`);
    } finally {
      setSaving(false);
    }
  }, [api, selectedLayer, layerContent]);

  const handleCreate = useCallback(async () => {
    if (!newLayerName.trim()) return;
    try {
      await createConfigLayer(api, newLayerName.trim());
      setNewLayerName("");
      setShowCreate(false);
      refetchLayers();
      setStatusMsg("Layer created");
    } catch (err) {
      setStatusMsg(`Error creating layer: ${err}`);
    }
  }, [api, newLayerName, refetchLayers]);

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Settings className="size-5" />
          <h1 className="text-2xl font-bold tracking-tight">Configuration</h1>
        </div>
        <Button size="sm" onClick={() => setShowCreate(!showCreate)}>
          <Plus className="mr-1 size-4" /> New Layer
        </Button>
      </div>

      {showCreate && (
        <Card>
          <CardContent className="flex items-center gap-3 pt-6">
            <Input
              placeholder="Layer name"
              value={newLayerName}
              onChange={(e) => setNewLayerName(e.target.value)}
              className="max-w-xs"
            />
            <Button size="sm" onClick={handleCreate}>
              Create
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setShowCreate(false)}
            >
              Cancel
            </Button>
          </CardContent>
        </Card>
      )}

      {statusMsg && (
        <div
          className={`rounded-md p-3 text-sm ${
            statusMsg.startsWith("Error")
              ? "bg-[hsl(var(--destructive)/0.1)] text-[hsl(var(--destructive))]"
              : "bg-[hsl(var(--success,142_76%_36%)/0.1)] text-[hsl(var(--success,142_76%_36%))]"
          }`}
        >
          {statusMsg}
        </div>
      )}

      <div className="grid gap-6 xl:grid-cols-4">
        <Card className="xl:col-span-1">
          <CardHeader>
            <CardTitle>Layers</CardTitle>
          </CardHeader>
          <CardContent>
            {layersLoading ? (
              <div className="space-y-2">
                {Array.from({ length: 3 }).map((_, i) => (
                  <Skeleton key={i} className="h-8" />
                ))}
              </div>
            ) : (
              <div className="space-y-1">
                {(layers ?? []).map((name) => (
                  <button
                    key={name}
                    onClick={() => loadLayer(name)}
                    className={`flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-sm transition-colors hover:bg-[hsl(var(--muted))] ${
                      selectedLayer === name
                        ? "bg-[hsl(var(--muted))] font-medium"
                        : ""
                    }`}
                  >
                    <FileText className="size-3.5" />
                    {name}
                    {name === "default" && (
                      <Badge variant="outline" className="ml-auto text-xs">
                        default
                      </Badge>
                    )}
                  </button>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="xl:col-span-3">
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle>
              {selectedLayer ? `Layer: ${selectedLayer}` : "Select a layer"}
            </CardTitle>
            {selectedLayer && (
              <Button
                size="sm"
                onClick={handleSave}
                disabled={saving || selectedLayer === "default"}
              >
                <Save className="mr-1 size-4" />
                {saving ? "Saving…" : "Save"}
              </Button>
            )}
          </CardHeader>
          <CardContent>
            {loadingLayer ? (
              <Skeleton className="h-96" />
            ) : selectedLayer ? (
              <Textarea
                value={layerContent}
                onChange={(e) => setLayerContent(e.target.value)}
                className="min-h-96 font-mono text-xs"
                disabled={selectedLayer === "default"}
              />
            ) : (
              <p className="text-sm text-[hsl(var(--muted-foreground))]">
                Select a configuration layer to view and edit.
              </p>
            )}
          </CardContent>
        </Card>
      </div>

      {topology && topology.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Topology</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {topology.map((entry, i) => (
                <div
                  key={i}
                  className="flex items-center gap-2 border-b border-[hsl(var(--border))] pb-2 last:border-0"
                >
                  <span className="font-medium">
                    {entry.Name || `Node ${entry.ID}`}
                  </span>
                  <span className="text-sm text-[hsl(var(--muted-foreground))]">
                    →
                  </span>
                  <div className="flex flex-wrap gap-1">
                    {entry.LayersCSV.split(",")
                      .filter(Boolean)
                      .map((layer) => (
                        <Badge key={layer} variant="outline">
                          {layer.trim()}
                        </Badge>
                      ))}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
