// src/layouts/app-layout.tsx
import { useState, useCallback, type ReactNode } from "react";
import { CollapsibleSidebar } from "./collapsible-sidebar";
import { useLayout } from "@/contexts/layout-context";
import {
  useConnectionStatus,
  type ConnectionStatus,
} from "@/contexts/curio-api-context";
import {
  Menu,
  ChevronLeft,
  Search,
  Sun,
  Moon,
  Settings,
} from "lucide-react";
import { cn } from "@/lib/utils";

function ConnectionStatusBadge({ status }: { status: ConnectionStatus }) {
  const colorMap: Record<ConnectionStatus, string> = {
    connected: "bg-[hsl(var(--success))]",
    connecting: "bg-[hsl(var(--warning))]",
    disconnected: "bg-[hsl(var(--destructive))]",
    reconnecting: "bg-[hsl(var(--warning))]",
  };

  const labelMap: Record<ConnectionStatus, string> = {
    connected: "Connected",
    connecting: "Connecting...",
    disconnected: "Disconnected",
    reconnecting: "Reconnecting...",
  };

  return (
    <div className="flex items-center gap-2 text-sm">
      <div className={cn("size-2 rounded-full", colorMap[status])} />
      <span className="text-[hsl(var(--muted-foreground))]">
        {labelMap[status]}
      </span>
    </div>
  );
}

export function AppLayout({ children }: { children: ReactNode }) {
  const layout = useLayout();
  const connectionStatus = useConnectionStatus();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const openSearch = useCallback(() => {
    // Trigger ⌘K which AppQuickSearch listens for
    document.dispatchEvent(
      new KeyboardEvent("keydown", { key: "k", metaKey: true }),
    );
  }, []);

  return (
    <div className="flex min-h-screen bg-[hsl(var(--background))]">
      {/* Desktop Sidebar */}
      <div className="fixed top-0 left-0 z-30 hidden lg:block">
        <CollapsibleSidebar
          isCollapsed={layout.sidebarCollapsed}
          onToggle={layout.toggleSidebar}
        />
      </div>

      {/* Mobile Drawer */}
      {mobileMenuOpen && (
        <div className="fixed inset-0 z-40 lg:hidden">
          <div
            className="absolute inset-0 bg-black/50"
            onClick={() => setMobileMenuOpen(false)}
          />
          <div className="relative z-50 w-64">
            <CollapsibleSidebar />
          </div>
        </div>
      )}

      {/* Mobile Top Bar */}
      <div className="w-full lg:hidden">
        <div className="border-b border-[hsl(var(--border))] bg-[hsl(var(--card))] px-4 py-3">
          <div className="flex items-center justify-between">
            <button
              onClick={() => setMobileMenuOpen(true)}
              className="rounded-md p-2 hover:bg-[hsl(var(--accent))]"
            >
              <Menu className="size-5" />
            </button>
            <div className="flex items-center gap-2">
              <div className="bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] grid size-7 place-items-center rounded-lg text-xs font-bold">
                C
              </div>
              <span className="font-semibold">Cuview</span>
            </div>
            <div className="w-9" />
          </div>
        </div>
        <main className="flex-1">{children}</main>
      </div>

      {/* Desktop Main Content */}
      <main
        className="hidden min-h-screen flex-1 transition-all duration-300 lg:block"
        style={{
          marginLeft: layout.sidebarCollapsed ? "4rem" : "16rem",
        }}
      >
        {/* Top Bar */}
        <div className="sticky top-0 z-20 border-b border-[hsl(var(--border))] bg-[hsl(var(--card))]/95 backdrop-blur-sm">
          <div className="flex items-center justify-between px-6 py-3">
            <div className="flex items-center gap-3">
              <button
                onClick={layout.toggleSidebar}
                className="rounded-md p-1.5 hover:bg-[hsl(var(--accent))]"
                title={
                  layout.sidebarCollapsed
                    ? "Expand sidebar"
                    : "Collapse sidebar"
                }
              >
                {layout.sidebarCollapsed ? (
                  <Menu className="size-5" />
                ) : (
                  <ChevronLeft className="size-5" />
                )}
              </button>
              <ConnectionStatusBadge status={connectionStatus} />
            </div>

            {/* Search */}
            <div className="mx-8 max-w-md flex-1">
              <button
                onClick={openSearch}
                className="border-[hsl(var(--input))] bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))] flex h-9 w-full items-center justify-between rounded-lg border px-3 text-left text-sm transition hover:border-[hsl(var(--ring))]"
              >
                <span className="flex items-center gap-2">
                  <Search className="size-4 opacity-50" />
                  <span className="truncate">
                    Search pages, actors, or task types
                  </span>
                </span>
                <kbd className="border-[hsl(var(--border))] bg-[hsl(var(--card))] pointer-events-none hidden rounded border px-1.5 py-0.5 text-xs sm:inline-flex">
                  ⌘K
                </kbd>
              </button>
            </div>

            {/* Actions */}
            <div className="flex items-center gap-1">
              <button
                onClick={layout.toggleTheme}
                className="rounded-md p-2 hover:bg-[hsl(var(--accent))]"
                title={
                  layout.isDark
                    ? "Switch to light mode"
                    : "Switch to dark mode"
                }
              >
                {layout.isDark ? (
                  <Sun className="size-5" />
                ) : (
                  <Moon className="size-5" />
                )}
              </button>
              <button
                className="rounded-md p-2 hover:bg-[hsl(var(--accent))]"
                title="Settings"
              >
                <Settings className="size-5" />
              </button>
            </div>
          </div>
        </div>

        {/* Page Content */}
        <div className="relative">{children}</div>
      </main>
    </div>
  );
}

// src/layouts/AppLayout.vue
<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from "vue";
import CollapsibleSidebar from "./CollapsibleSidebar.vue";
import SettingsModal from "@/components/composed/SettingsModal.vue";
import AppQuickSearch from "@/components/composed/AppQuickSearch.vue";
import ConnectionStatus from "@/components/ui/ConnectionStatus.vue";
import ThemeToggle from "@/components/ui/ThemeToggle.vue";
import NetworkSimulationToggle from "@/components/ui/NetworkSimulationToggle.vue";
import ActiveTasksDropdown from "@/components/composed/ActiveTasksDropdown.vue";
import {
  Bars3Icon,
  ChevronLeftIcon,
  MagnifyingGlassIcon,
  BellIcon,
  Cog6ToothIcon,
} from "@heroicons/vue/24/outline";

import { useLayoutStore } from "@/stores/layout";

const mobileMenuOpen = ref(false);
const layoutStore = useLayoutStore();
const settingsModalOpen = ref(false);
const quickSearchOpen = ref(false);

const mainContentMargin = computed(() =>
  layoutStore.sidebarCollapsed ? "4rem" : "16rem",
);

const handleNotifications = () => {
  console.log("Open notifications");
};

const handleSettings = () => {
  settingsModalOpen.value = true;
};

const openQuickSearch = () => {
  quickSearchOpen.value = true;
};

const handleShortcut = (event: KeyboardEvent) => {
  const key = event.key.toLowerCase();
  if ((event.metaKey || event.ctrlKey) && key === "k") {
    event.preventDefault();
    quickSearchOpen.value = true;
  }
};

onMounted(() => {
  window.addEventListener("keydown", handleShortcut);
});

onBeforeUnmount(() => {
  window.removeEventListener("keydown", handleShortcut);
});
</script>

<template>
  <div class="bg-base-300 flex min-h-screen">
    <div class="fixed top-0 left-0 z-30 hidden lg:block">
      <CollapsibleSidebar :is-collapsed="layoutStore.sidebarCollapsed" />
    </div>

    <div class="w-full lg:hidden">
      <div class="drawer">
        <input
          id="mobile-drawer-toggle"
          v-model="mobileMenuOpen"
          type="checkbox"
          class="drawer-toggle"
        />

        <div class="drawer-content flex flex-col">
          <div class="navbar bg-base-100 shadow-sm">
            <div class="navbar-start">
              <label
                for="mobile-drawer-toggle"
                class="btn btn-square btn-ghost"
              >
                <Bars3Icon class="size-6" />
              </label>
            </div>
            <div class="navbar-center">
              <div class="flex items-center gap-2">
                <div
                  class="bg-primary text-primary-content grid size-8 place-items-center rounded-lg font-semibold"
                >
                  C
                </div>
                <span class="text-lg font-semibold">Cuview</span>
              </div>
            </div>
            <div class="navbar-end"></div>
          </div>

          <main class="flex-1">
            <slot />
          </main>
        </div>

        <div class="drawer-side">
          <label
            for="mobile-drawer-toggle"
            aria-label="close sidebar"
            class="drawer-overlay"
          ></label>
          <div class="w-64">
            <CollapsibleSidebar />
          </div>
        </div>
      </div>
    </div>

    <main
      class="hidden min-h-screen flex-1 transition-all duration-300 lg:block"
      :style="{ marginLeft: mainContentMargin }"
    >
      <div
        class="bg-base-100 border-base-300 sticky top-0 z-20 border-b shadow-sm backdrop-blur-md"
      >
        <div class="flex items-center justify-between px-6 py-3">
          <div class="flex items-center gap-3">
            <button
              class="btn btn-ghost btn-sm size-9 p-0"
              :title="
                layoutStore.sidebarCollapsed
                  ? 'Expand sidebar'
                  : 'Collapse sidebar'
              "
              @click="layoutStore.toggleSidebar"
            >
              <Bars3Icon v-if="layoutStore.sidebarCollapsed" class="size-5" />
              <ChevronLeftIcon v-else class="size-5" />
            </button>

            <ConnectionStatus />
          </div>

          <div class="mx-8 max-w-md flex-1">
            <button
              type="button"
              class="bg-base-200 border-base-300 hover:border-primary focus-visible:ring-primary/40 focus-visible:ring-offset-base-100 text-base-content/70 flex h-9 w-full items-center justify-between rounded-lg border px-3 text-left text-sm transition focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none"
              @click="openQuickSearch"
            >
              <span class="flex items-center gap-2">
                <MagnifyingGlassIcon class="text-base-content/50 size-4" />
                <span class="truncate"
                  >Search pages, actors, or task types</span
                >
              </span>
              <kbd class="kbd kbd-xs hidden sm:inline-flex">⌘K</kbd>
            </button>
          </div>

          <div class="flex items-center gap-1">
            <div class="flex items-center gap-1">
              <button
                class="btn btn-ghost btn-sm relative size-9 p-0"
                title="Notifications"
                @click="handleNotifications"
              >
                <BellIcon class="size-5" />
                <div
                  class="bg-warning absolute -top-1 -right-1 size-3 rounded-full"
                ></div>
              </button>

              <ActiveTasksDropdown />

              <ThemeToggle />

              <NetworkSimulationToggle />

              <button
                class="btn btn-ghost btn-sm size-9 p-0"
                title="Settings"
                @click="handleSettings"
              >
                <Cog6ToothIcon class="size-5" />
              </button>
            </div>
          </div>
        </div>
      </div>

      <div class="relative">
        <slot />
      </div>
    </main>

    <SettingsModal v-model:open="settingsModalOpen" />
    <AppQuickSearch v-model:open="quickSearchOpen" />
  </div>
</template>
