// src/layouts/collapsible-sidebar.tsx
import { Link, useRouterState } from "@tanstack/react-router";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { cn } from "@/lib/utils";
import { type NavigationEntry, navigationGroups } from "./navigation";

interface CollapsibleSidebarProps {
  isCollapsed?: boolean;
  onToggle?: () => void;
}

export function CollapsibleSidebar({
  isCollapsed = false,
  onToggle,
}: CollapsibleSidebarProps) {
  const routerState = useRouterState();
  const currentPath = routerState.location.pathname;

  const isActive = (entry: NavigationEntry) => {
    if (entry.activePattern) {
      return new RegExp(entry.activePattern).test(currentPath);
    }
    return currentPath === entry.to || currentPath.startsWith(`${entry.to}/`);
  };

  return (
    <aside
      className={cn(
        "bg-sidebar border-r border-sidebar-border flex h-screen flex-col transition-all duration-300",
        isCollapsed ? "w-16" : "w-64",
      )}
    >
      {/* Logo */}
      <div className="flex h-14 items-center border-b border-sidebar-border px-4">
        <div className="flex items-center gap-3">
          <div className="bg-primary text-primary-foreground grid size-8 shrink-0 place-items-center rounded-lg text-sm font-bold">
            C
          </div>
          {!isCollapsed && (
            <span className="text-sidebar-foreground text-lg font-semibold">
              Cuview
            </span>
          )}
        </div>
      </div>

      {/* Navigation */}
      <nav className="flex-1 overflow-y-auto p-2">
        {navigationGroups.map((group, groupIdx) => (
          <div key={group.title}>
            {groupIdx > 0 && (
              <div className="border-t border-sidebar-border my-2" />
            )}
            {!isCollapsed && (
              <div className="text-sidebar-foreground/0.5 px-3 pt-2 pb-1 text-xs font-semibold uppercase tracking-wider">
                {group.title}
              </div>
            )}
            <ul className="space-y-1">
              {group.entries.map((entry) => {
                const Icon = entry.icon;
                const active = isActive(entry);
                return (
                  <li key={entry.to}>
                    <Link
                      to={entry.to}
                      className={cn(
                        "flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium transition-colors",
                        active
                          ? "bg-sidebar-accent text-sidebar-accent-foreground"
                          : "text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground",
                        isCollapsed && "justify-center px-2",
                      )}
                      title={isCollapsed ? entry.label : undefined}
                    >
                      <Icon className="size-5 shrink-0" />
                      {!isCollapsed && <span>{entry.label}</span>}
                    </Link>
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </nav>

      {/* Collapse toggle */}
      {onToggle && (
        <div className="border-t border-sidebar-border p-2">
          <button
            onClick={onToggle}
            className="text-sidebar-foreground hover:bg-sidebar-accent flex w-full items-center justify-center rounded-md p-2 transition-colors"
            title={isCollapsed ? "Expand sidebar" : "Collapse sidebar"}
          >
            {isCollapsed ? (
              <ChevronRight className="size-4" />
            ) : (
              <ChevronLeft className="size-4" />
            )}
          </button>
        </div>
      )}
    </aside>
  );
}

// src/layouts/CollapsibleSidebar.vue
<script setup lang="ts">
import { computed } from "vue";
import { useRoute } from "vue-router";
import { navigationEntries, type NavigationEntry } from "./navigation";

const navItems = navigationEntries;

const { isCollapsed = false } = defineProps<{
  isCollapsed?: boolean;
}>();

const route = useRoute();

// Check if navigation item should be active
const isNavItemActive = (item: NavigationEntry): boolean => {
  if (item.activePattern) {
    // If has custom active pattern, use regex matching
    const pattern = new RegExp(item.activePattern);
    return pattern.test(route.path);
  }
  // Otherwise use exact matching
  return route.path === item.to;
};

const sidebarClasses = computed(() => [
  "transition-all duration-300 ease-in-out bg-base-100 shadow-xl h-screen flex flex-col",
  isCollapsed ? "w-16" : "w-64",
]);
</script>

<template>
  <aside :class="sidebarClasses">
    <div class="border-base-300 flex h-20 flex-col justify-center border-b p-4">
      <div v-if="!isCollapsed" class="flex items-center gap-3">
        <div
          class="bg-neutral text-neutral-content grid size-10 place-items-center rounded-xl text-lg font-bold"
        >
          C
        </div>
        <div>
          <h1 class="text-lg font-bold">Cuview</h1>
        </div>
      </div>

      <div v-else class="flex items-center justify-center">
        <div
          class="bg-neutral text-neutral-content grid size-10 place-items-center rounded-xl text-lg font-bold"
        >
          C
        </div>
      </div>
    </div>

    <nav class="flex-1" :class="isCollapsed ? 'p-2' : 'p-4'">
      <div class="space-y-1">
        <template v-for="item in navItems" :key="item.label">
          <div class="relative">
            <router-link
              :to="item.to"
              class="group relative flex h-10 items-center rounded-lg text-sm font-medium transition-all duration-200"
              :class="[
                isCollapsed ? 'w-10 justify-center px-2' : 'gap-3 px-3',
                isNavItemActive(item)
                  ? 'bg-neutral text-neutral-content hover:bg-neutral-focus shadow-inner'
                  : 'text-base-content/80 hover:bg-base-200',
              ]"
              :title="isCollapsed ? item.label : ''"
            >
              <component :is="item.icon" class="size-5 shrink-0" />

              <!-- Text container only when expanded -->
              <div v-if="!isCollapsed" class="flex min-w-0 flex-1 items-center">
                <Transition name="slide-left">
                  <span v-if="!isCollapsed" class="truncate">{{
                    item.label
                  }}</span>
                </Transition>
              </div>
            </router-link>

            <Transition name="tooltip">
              <div
                v-if="isCollapsed"
                class="tooltip bg-neutral text-neutral-content absolute top-1/2 left-full z-50 ml-2 -translate-y-1/2 rounded px-2 py-1 text-xs whitespace-nowrap shadow-lg"
              >
                {{ item.label }}
              </div>
            </Transition>
          </div>
        </template>
      </div>
    </nav>
  </aside>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.slide-left-enter-active,
.slide-left-leave-active {
  transition: all 0.3s ease;
}
.slide-left-enter-from {
  opacity: 0;
  transform: translateX(-10px);
}
.slide-left-leave-to {
  opacity: 0;
  transform: translateX(-10px);
}

.tooltip-enter-active,
.tooltip-leave-active {
  transition: opacity 0.2s ease;
}
.tooltip-enter-from,
.tooltip-leave-to {
  opacity: 0;
}

.tooltip {
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.2s ease;
}

.group:hover .tooltip {
  opacity: 1;
}

.btn {
  position: relative;
  z-index: 10;
}
</style>
